# Generated by Django 6.0.4 on 2026-05-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del servidor')),
                ('url', models.URLField(verbose_name='URL de comprobación')),
                ('restart_command', models.TextField(help_text='Comando shell que se ejecutará para reiniciar Odoo. Ej: sudo systemctl restart odoo', verbose_name='Comando de reinicio')),
                ('check_interval', models.PositiveIntegerField(default=5, help_text='Cada cuántos minutos se comprobará la URL', verbose_name='Intervalo de chequeo (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Monitoreo activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de servidor',
                'verbose_name_plural': 'Configuraciones de servidores',
                'ordering': ['name'],
            },
        ),
    ]
