# Generated by Django 6.0.4 on 2026-05-03 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último chequeo'),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='last_status',
            field=models.CharField(choices=[('unknown', 'Desconocido'), ('online', 'En línea'), ('offline', 'Fuera de línea')], default='unknown', max_length=10, verbose_name='Último estado'),
        ),
        migrations.CreateModel(
            name='ServerCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de chequeo')),
                ('status', models.CharField(choices=[('online', 'En línea'), ('offline', 'Fuera de línea'), ('error', 'Error')], max_length=10, verbose_name='Estado')),
                ('http_code', models.IntegerField(blank=True, null=True, verbose_name='Código HTTP')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('restart_triggered', models.BooleanField(default=False, verbose_name='Reinicio disparado')),
                ('restart_success', models.BooleanField(blank=True, null=True, verbose_name='Reinicio exitoso')),
                ('restart_output', models.TextField(blank=True, verbose_name='Salida del comando')),
                ('error_detail', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='core.serverconfig', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Log de chequeo',
                'verbose_name_plural': 'Logs de chequeos',
                'ordering': ['-checked_at'],
            },
        ),
    ]
