# Generated by Django 6.0.4 on 2026-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serverconfig_last_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverchecklog',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Reinicio manual'),
        ),
    ]
