# Generated by Django 6.0.4 on 2026-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_manual_to_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReadCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_file', models.CharField(max_length=255, unique=True, verbose_name='Archivo de log')),
                ('last_position', models.BigIntegerField(default=0, verbose_name='Última posición (bytes)')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Última lectura')),
            ],
            options={
                'verbose_name': 'Cursor de log',
                'verbose_name_plural': 'Cursores de log',
            },
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='restart_command',
            field=models.TextField(help_text='Comando shell ejecutado en el sistema host (no dentro de Docker). Ejemplos: «docker restart odoo» · «docker compose -f /srv/odoo/docker-compose.yml restart» · «sudo systemctl restart odoo»', verbose_name='Comando de reinicio'),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ssh_fail', 'Login SSH fallido'), ('ssh_success', 'Login SSH exitoso'), ('ssh_invalid', 'Usuario inválido SSH'), ('sudo', 'Uso de sudo'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Fecha del evento')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Usuario')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP origen')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='Hostname')),
                ('raw_line', models.TextField(verbose_name='Línea original')),
                ('log_file', models.CharField(max_length=255, verbose_name='Archivo de log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de seguridad',
                'verbose_name_plural': 'Eventos de seguridad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='core_securi_timesta_caaa4f_idx')],
            },
        ),
    ]
