# Generated by Django 6.0.4 on 2026-05-03 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_security_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Odoo Server', max_length=150, verbose_name='Nombre')),
                ('log_path', models.CharField(default='/var/log/odoo/odoo-server.log', help_text='Ruta absoluta en el sistema host, ej. /var/log/odoo/odoo-server.log', max_length=500, verbose_name='Ruta del archivo de log')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuente de log Odoo',
                'verbose_name_plural': 'Fuentes de log Odoo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OdooLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Fecha del evento')),
                ('level', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('INFO', 'Info'), ('DEBUG', 'Debug')], db_index=True, max_length=10, verbose_name='Nivel')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='PID')),
                ('database', models.CharField(blank=True, max_length=150, verbose_name='Base de datos')),
                ('logger', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Logger')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('raw_line', models.TextField(verbose_name='Línea original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.odoologsource', verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Entrada de log Odoo',
                'verbose_name_plural': 'Entradas de log Odoo',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'level'], name='core_odoolo_timesta_72c0c9_idx')],
            },
        ),
    ]
