# Generated by Django 6.0.4 on 2026-05-03 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_odoo_log_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Comando')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], db_index=True, default='manual', max_length=10, verbose_name='Origen')),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de ejecución')),
                ('success', models.BooleanField(verbose_name='Exitoso')),
                ('output', models.TextField(blank=True, verbose_name='Salida del comando')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_logs', to='core.serverconfig', verbose_name='Servidor')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
            ],
            options={
                'verbose_name': 'Historial de comando',
                'verbose_name_plural': 'Historial de comandos',
                'ordering': ['-executed_at'],
            },
        ),
    ]
