# Generated by Django 6.0.4 on 2026-05-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_command_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(choices=[('check_all_servers', 'Chequeo de servidores Odoo'), ('read_security_logs', 'Lectura de logs de seguridad'), ('read_odoo_logs', 'Lectura de logs de aplicación Odoo')], db_index=True, max_length=60, verbose_name='Tarea')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(verbose_name='Fin')),
                ('duration_ms', models.IntegerField(verbose_name='Duración (ms)')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], db_index=True, default='ok', max_length=10)),
                ('detail', models.TextField(blank=True, verbose_name='Detalle / error')),
            ],
            options={
                'verbose_name': 'Ejecución del scheduler',
                'verbose_name_plural': 'Ejecuciones del scheduler',
                'ordering': ['-started_at'],
            },
        ),
    ]
