# Generated by Django 6.0.4 on 2026-05-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_scheduler_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='Fecha')),
                ('cpu_percent', models.FloatField(verbose_name='CPU %')),
                ('ram_percent', models.FloatField(verbose_name='RAM %')),
            ],
            options={
                'verbose_name': 'Métrica del sistema',
                'verbose_name_plural': 'Métricas del sistema',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AlterField(
            model_name='schedulerlog',
            name='job_id',
            field=models.CharField(choices=[('read_security_logs', 'Lectura de logs de seguridad'), ('read_odoo_logs', 'Lectura de logs de aplicación Odoo')], db_index=True, max_length=60, verbose_name='Tarea'),
        ),
    ]
